[project]
name = "building-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "einops>=0.8.1",
    "numpy>=2.3.2",
    "regex>=2025.8.29",
    "torch>=2.8.0",
    "tqdm>=4.67.1",
]
